# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--config=.flake8]

  - repo: https://github.com/pycqa/pylint
    rev: v3.2.7
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
        exclude: tests/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: myvenv/bin/mypy
        language: system
        types: [python]
        pass_filenames: true
        args: [--ignore-missing-imports]

      - id: vulture
        name: vulture
        entry: myvenv/bin/vulture
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual]
        args: ["--exclude", "myvenv", "--min-confidence", "100", "."]

      - id: pytest
        name: pytest
        entry: env PYTHONPATH=. myvenv/bin/pytest --cov=. --cov-report=term-missing --cov-fail-under=20
        language: system
        pass_filenames: false
        always_run: true

      - id: bandit
        name: bandit
        entry: myvenv/bin/bandit
        language: system
        types: [python]
        pass_filenames: true
        args: ["-r", "-ll", "-c", "bandit.yaml"]

      - id: pip-audit
        name: pip-audit
        entry: myvenv/bin/pip-audit
        language: system
        pass_filenames: false
        always_run: true
        args: [ "--ignore-vuln", "CVE-2026-45829" ]
