[git]
conventional_commits = true
filter_unconventional = true
tag_prefix = "v"

[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% endfor %}
"""

[sections]
"Features" = ["feat"]
"Bug Fixes" = ["fix"]
"Documentation" = ["docs"]
"Performance" = ["perf"]
